import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Header from '@/components/publicLayout/Header';
import type { Metadata } from 'next';
import Footer from '@/components/publicLayout/Footer';
import Providers from '@/providers';
import { Toaster } from '@/components/ui/toast';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'GridCare',
    description: 'Generated by GridCare',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
    return (
        <html
            lang="en"
            className={cn(
                'h-full',
                'antialiased',
                geistSans.variable,
                geistMono.variable,
                'font-sans',
                inter.variable,
            )}
        >
            <Providers>
                <body className="flex min-h-screen flex-col">
                    <Header />
                    <main className="flex-1">
                        {children}
                        <Toaster />
                    </main>
                    <Footer />
                </body>
            </Providers>
        </html>
    );
}
